gw_app:


  #API   setting
    api_port: 7777
    session_expire_days: 1
    hot_count: 1000
    template_dir: templates/
    static_dir: statics/
    favicon_path: favicon
    cookie_secret: projectkuo

    client_version: 1
    download_url: http://52.4.126.34:8088/api/v1/web/download
    debug: 1
    ###  mqtt###
    mqtt:
      local_mqtt_auto_connect : True
      local_mqtt_client_id : 'local_GW'
      local_mqtt_host : 192.168.30.55
      #local_ host : 192.168.30.201
      local_mqtt_port: 1883
      local_mqtt_keepalive : 60

      cloud_mqtt_auto_connect : True
      cloud_mqtt_client_id : 'local_GW'
      cloud_mqtt_host : 192.168.30.250
      #local_ host : 192.168..201
      cloud_mqtt_port: 1883
      cloud_mqtt_keepalive : 60




